Repository solana-labs/solana-web3.js, pull requests merged in 2023-12, with the labels that each got.

#1865 refactor(experimental): pre-build the byte array before encoding with codecs
  packages/codecs-core/src/__tests__/__setup__.ts
  packages/codecs-core/src/__tests__/codec-test.ts
  packages/codecs-core/src/__tests__/combine-codec.ts
  packages/codecs-core/src/__tests__/fix-codec-test.ts
  packages/codecs-core/src/__tests__/map-codec-test.ts
  packages/codecs-core/src/__tests__/reverse-codec-test.ts
  packages/codecs-core/src/assertions.ts
  packages/codecs-core/src/codec.ts
  packages/codecs-core/src/combine-codec.ts
  packages/codecs-core/src/fix-codec.ts
  packages/codecs-core/src/map-codec.ts
  packages/codecs-core/src/reverse-codec.ts
Labels: community

#1903 refactor(experimental): remove `{ fixedSize: null }` from variable size codecs
  packages/codecs-core/src/__tests__/__setup__.ts
  packages/codecs-core/src/__tests__/codec-test.ts
  packages/codecs-core/src/__tests__/combine-codec.ts
  packages/codecs-core/src/__tests__/map-codec-test.ts
  packages/codecs-core/src/__typetests__/codec-typetest.ts
  packages/codecs-core/src/assertions.ts
  packages/codecs-core/src/codec.ts
  packages/codecs-core/src/combine-codec.ts
  packages/codecs-core/src/fix-codec.ts
  packages/codecs-core/src/map-codec.ts
  packages/codecs-core/src/reverse-codec.ts
  packages/codecs-numbers/src/__tests__/__setup__.ts
  packages/codecs-numbers/src/__tests__/short-u16-test.ts
  packages/codecs-numbers/src/short-u16.ts
  packages/codecs-strings/src/__tests__/string-test.ts
  packages/codecs-strings/src/base16.ts
  packages/codecs-strings/src/base64.ts
  packages/codecs-strings/src/baseX-reslice.ts
  packages/codecs-strings/src/baseX.ts
  packages/codecs-strings/src/string.ts
  packages/codecs-strings/src/utf8.ts
Labels: community

#1909 refactor(experimental): add size type param to fixed-size codecs
  packages/codecs-core/src/__typetests__/codec-typetest.ts
  packages/codecs-core/src/__typetests__/combine-codec-typetest.ts
  packages/codecs-core/src/__typetests__/fix-codec-typetest.ts
  packages/codecs-core/src/__typetests__/map-codec-typetest.ts
  packages/codecs-core/src/__typetests__/reverse-codec-typetest.ts
  packages/codecs-core/src/codec.ts
  packages/codecs-core/src/combine-codec.ts
  packages/codecs-core/src/fix-codec.ts
  packages/codecs-core/src/map-codec.ts
  packages/codecs-core/src/reverse-codec.ts
  packages/codecs-numbers/src/common.ts
  packages/codecs-numbers/src/f32.ts
  packages/codecs-numbers/src/f64.ts
  packages/codecs-numbers/src/i128.ts
  packages/codecs-numbers/src/i16.ts
  packages/codecs-numbers/src/i32.ts
  packages/codecs-numbers/src/i64.ts
  packages/codecs-numbers/src/i8.ts
  packages/codecs-numbers/src/u128.ts
  packages/codecs-numbers/src/u16.ts
  packages/codecs-numbers/src/u32.ts
  packages/codecs-numbers/src/u64.ts
  packages/codecs-numbers/src/u8.ts
  packages/codecs-numbers/src/utils.ts
  packages/codecs-strings/src/__typetests__/string-typetest.ts
  packages/codecs-strings/src/string.ts
Labels: community

#1923 refactor(experimental): bring `jsonParsed` types to parity
  packages/rpc-core/src/rpc-methods/common-transactions.ts
  packages/rpc-core/src/rpc-methods/common.ts
Labels: community

#1855 refactor(experimental): add accounts package
  packages/accounts/.gitignore
  packages/accounts/.prettierignore
  packages/accounts/LICENSE
  packages/accounts/README.md
  packages/accounts/package.json
  packages/accounts/src/__tests__/__setup__.ts
  packages/accounts/src/__tests__/decode-account-test.ts
  packages/accounts/src/__tests__/fetch-account-test.ts
  packages/accounts/src/__tests__/maybe-account-test.ts
  packages/accounts/src/__tests__/parse-account-test.ts
  packages/accounts/src/__typetests__/decode-account-typetest.ts
  packages/accounts/src/__typetests__/fetch-account-typetest.ts
  packages/accounts/src/__typetests__/parse-account-typetest.ts
  packages/accounts/src/account.ts
  packages/accounts/src/decode-account.ts
  packages/accounts/src/fetch-account.ts
  packages/accounts/src/index.ts
  packages/accounts/src/maybe-account.ts
  packages/accounts/src/parse-account.ts
  packages/accounts/src/types/global.d.ts
  packages/accounts/tsconfig.declarations.json
  packages/accounts/tsconfig.json
  pnpm-lock.yaml
Labels: community

#1907 refactor(experimental): add build script that adds .js to type imports
  packages/accounts/package.json
  packages/addresses/package.json
  packages/assertions/package.json
  packages/build-scripts/add-js-extension-to-types.mjs
  packages/build-scripts/package.json
  packages/codecs-core/package.json
  packages/codecs-data-structures/package.json
  packages/codecs-numbers/package.json
  packages/codecs-strings/package.json
  packages/compat/package.json
  packages/functional/package.json
  packages/instructions/package.json
  packages/keys/package.json
  packages/library-legacy-sham/package.json
  packages/library/package.json
  packages/options/package.json
  packages/rpc-core/package.json
  packages/rpc-graphql/package.json
  packages/rpc-transport/package.json
  packages/rpc-types/package.json
  packages/signers/package.json
  packages/transactions/package.json
  packages/webcrypto-ed25519-polyfill/package.json
Labels: community

#1958 refactor(experimental): `crypto-impl` is a private package and should not be a dependency of the polyfill
  packages/webcrypto-ed25519-polyfill/package.json
  pnpm-lock.yaml
Labels: automerge

#1961 Minor Corrections and Improvements to Code Examples and Documentation
  packages/compat/README.md
  packages/library-legacy/README.md
  packages/library/README.md
Labels: automerge, community

#1843 refactor(experimental): make RPC methods extend `IRpcApiMethods`
  packages/rpc-core/src/rpc-methods/getAccountInfo.ts
  packages/rpc-core/src/rpc-methods/getBalance.ts
  packages/rpc-core/src/rpc-methods/getBlock.ts
  packages/rpc-core/src/rpc-methods/getBlockCommitment.ts
  packages/rpc-core/src/rpc-methods/getBlockHeight.ts
  packages/rpc-core/src/rpc-methods/getBlockProduction.ts
  packages/rpc-core/src/rpc-methods/getBlockTime.ts
  packages/rpc-core/src/rpc-methods/getBlocks.ts
  packages/rpc-core/src/rpc-methods/getBlocksWithLimit.ts
  packages/rpc-core/src/rpc-methods/getClusterNodes.ts
  packages/rpc-core/src/rpc-methods/getEpochInfo.ts
  packages/rpc-core/src/rpc-methods/getEpochSchedule.ts
  packages/rpc-core/src/rpc-methods/getFeeForMessage.ts
  packages/rpc-core/src/rpc-methods/getFirstAvailableBlock.ts
  packages/rpc-core/src/rpc-methods/getGenesisHash.ts
  packages/rpc-core/src/rpc-methods/getHealth.ts
  packages/rpc-core/src/rpc-methods/getHighestSnapshotSlot.ts
  packages/rpc-core/src/rpc-methods/getIdentity.ts
  packages/rpc-core/src/rpc-methods/getInflationGovernor.ts
  packages/rpc-core/src/rpc-methods/getInflationRate.ts
  packages/rpc-core/src/rpc-methods/getInflationReward.ts
  packages/rpc-core/src/rpc-methods/getLargestAccounts.ts
  packages/rpc-core/src/rpc-methods/getLatestBlockhash.ts
  packages/rpc-core/src/rpc-methods/getLeaderSchedule.ts
  packages/rpc-core/src/rpc-methods/getMaxRetransmitSlot.ts
  packages/rpc-core/src/rpc-methods/getMaxShredInsertSlot.ts
  packages/rpc-core/src/rpc-methods/getMinimumBalanceForRentExemption.ts
  packages/rpc-core/src/rpc-methods/getMultipleAccounts.ts
  packages/rpc-core/src/rpc-methods/getProgramAccounts.ts
  packages/rpc-core/src/rpc-methods/getRecentPerformanceSamples.ts
  packages/rpc-core/src/rpc-methods/getRecentPrioritizationFees.ts
  packages/rpc-core/src/rpc-methods/getSignatureStatuses.ts
  packages/rpc-core/src/rpc-methods/getSignaturesForAddress.ts
  packages/rpc-core/src/rpc-methods/getSlot.ts
  packages/rpc-core/src/rpc-methods/getSlotLeader.ts
  packages/rpc-core/src/rpc-methods/getSlotLeaders.ts
  packages/rpc-core/src/rpc-methods/getStakeActivation.ts
  packages/rpc-core/src/rpc-methods/getStakeMinimumDelegation.ts
  packages/rpc-core/src/rpc-methods/getSupply.ts
  packages/rpc-core/src/rpc-methods/getTokenAccountBalance.ts
  packages/rpc-core/src/rpc-methods/getTokenAccountsByDelegate.ts
  packages/rpc-core/src/rpc-methods/getTokenAccountsByOwner.ts
  packages/rpc-core/src/rpc-methods/getTokenLargestAccounts.ts
  packages/rpc-core/src/rpc-methods/getTokenSupply.ts
  packages/rpc-core/src/rpc-methods/getTransaction.ts
  packages/rpc-core/src/rpc-methods/getTransactionCount.ts
  packages/rpc-core/src/rpc-methods/getVersion.ts
  packages/rpc-core/src/rpc-methods/getVoteAccounts.ts
  packages/rpc-core/src/rpc-methods/index.ts
  packages/rpc-core/src/rpc-methods/isBlockhashValid.ts
  packages/rpc-core/src/rpc-methods/minimumLedgerSlot.ts
  packages/rpc-core/src/rpc-methods/requestAirdrop.ts
  packages/rpc-core/src/rpc-methods/sendTransaction.ts
  packages/rpc-core/src/rpc-methods/simulateTransaction.ts
  packages/rpc-transport/src/apis/api-types.ts
  packages/rpc-transport/src/index.ts
Labels: community, do-not-close

#1846 refactor(experimental): rename `*Processor` to `*Transformer`
  packages/rpc-core/src/rpc-methods/index.ts
  packages/rpc-core/src/rpc-subscriptions/index.ts
  packages/rpc-transport/README.md
  packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
  packages/rpc-transport/src/__tests__/json-rpc-test.ts
  packages/rpc-transport/src/json-rpc-subscription.ts
  packages/rpc-transport/src/json-rpc-types.ts
  packages/rpc-transport/src/json-rpc.ts
Labels: community, do-not-close

#1781 refactor(experimental): add generic `createJsonRpcApi` function for custom APIs
  packages/rpc-core/src/rpc-methods/index.ts
  packages/rpc-transport/src/__tests__/json-rpc-test.ts
  packages/rpc-transport/src/apis/__typetests__/methods-api-typetest.ts
  packages/rpc-transport/src/apis/methods/methods-api.ts
  packages/rpc-transport/src/index.ts
  packages/rpc-transport/src/json-rpc-types.ts
  packages/rpc-transport/src/json-rpc.ts
Labels: community, do-not-close

#1844 refactor(experimental): make RPC subscription methods extend `IRpcSubscriptionsApiMethods`
  packages/rpc-core/src/rpc-subscriptions/account-notifications.ts
  packages/rpc-core/src/rpc-subscriptions/block-notifications.ts
  packages/rpc-core/src/rpc-subscriptions/index.ts
  packages/rpc-core/src/rpc-subscriptions/logs-notifications.ts
  packages/rpc-core/src/rpc-subscriptions/program-notifications.ts
  packages/rpc-core/src/rpc-subscriptions/root-notifications.ts
  packages/rpc-core/src/rpc-subscriptions/signature-notifications.ts
  packages/rpc-core/src/rpc-subscriptions/slot-notifications.ts
  packages/rpc-transport/src/apis/api-types.ts
Labels: community, do-not-close

#1845 refactor(experimental): add generic `createJsonRpcSubscriptionsApi` for custom APIs
  packages/rpc-core/src/rpc-subscriptions/index.ts
  packages/rpc-transport/src/__tests__/json-rpc-subscription-test.ts
  packages/rpc-transport/src/apis/__typetests__/subscriptions-api-typetest.ts
  packages/rpc-transport/src/apis/api-types.ts
  packages/rpc-transport/src/apis/subscriptions/subscriptions-api.ts
  packages/rpc-transport/src/index.ts
  packages/rpc-transport/src/json-rpc-subscription.ts
  packages/rpc-transport/src/json-rpc-types.ts
Labels: community, do-not-close

#1968 chore: fix typos
  README.md
  packages/addresses/README.md
  packages/library/README.md
  packages/rpc-types/README.md
Labels: community

#1982 refactor(experimental): close leaky open handles in subscriptions tests
  packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/slots-updates-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/vote-notifications-test.ts
Labels: community

#1983 refactor(experimental): wrap subscription tests in `try...finally`
  packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/slots-updates-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/vote-notifications-test.ts
Labels: community
