Repository solana-labs/solana-web3.js, pull requests merged in 2024-04, with the labels that each got.

#2404 chore: update `wait-on`
  pnpm-lock.yaml
Labels: automerge

#2394 refactor(experimental): add getLiteralUnionCodec to @solana/codecs-data-structures
  .changeset/tender-turtles-bake.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/literal-union-test.ts
  packages/codecs-data-structures/src/__typetests__/literal-union-typetest.ts
  packages/codecs-data-structures/src/literal-union.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2395 refactor(experimental): support more scalar values in getDiscriminatedUnionCodec
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
  packages/codecs-data-structures/src/discriminated-union.ts
  packages/errors/src/context.ts
Labels: community

#2396 refactor(experimental): nit: extract any types to local codec types
  packages/codecs-core/src/offset-codec.ts
  packages/codecs-core/src/pad-codec.ts
  packages/codecs-core/src/resize-codec.ts
Labels: community

#2397 refactor(experimental): add prefixCodec to @solana/codecs-core
  .changeset/chatty-flies-end.md
  packages/codecs-core/README.md
  packages/codecs-core/src/__tests__/prefix-codec-test.ts
  packages/codecs-core/src/__typetests__/prefix-codec-typetest.ts
  packages/codecs-core/src/index.ts
  packages/codecs-core/src/prefix-codec.ts
  packages/codecs-data-structures/src/__tests__/bytes-test.ts
  packages/codecs-data-structures/src/bytes.ts
  packages/codecs-strings/src/string.ts
  packages/codecs/README.md
Labels: community

#2398 refactor(experimental): add getUnionCodec to @solana/codecs-data-structures
  .changeset/nervous-deers-roll.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/union-test.ts
  packages/codecs-data-structures/src/__typetests__/union-typetest.ts
  packages/codecs-data-structures/src/index.ts
  packages/codecs-data-structures/src/union.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2399 refactor(experimental): refactor getDiscriminatedUnionCodec by using new getUnionCodec primitive
  packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
  packages/codecs-data-structures/src/discriminated-union.ts
Labels: community

#2400 refactor(experimental): add getConstantCodec to @solana/codecs-data-structures
  .changeset/honest-rivers-deny.md
  packages/codecs-core/README.md
  packages/codecs-core/src/bytes.ts
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/constant-test.ts
  packages/codecs-data-structures/src/__typetests__/constant-typetest.ts
  packages/codecs-data-structures/src/constant.ts
  packages/codecs-data-structures/src/index.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2409 refactor(experimental): refactor getNullableCodec and getOptionCodec to use getUnionCodec
  packages/codecs-data-structures/src/__tests__/nullable-test.ts
  packages/codecs-data-structures/src/nullable.ts
  packages/options/package.json
  packages/options/src/__tests__/option-codec-test.ts
  packages/options/src/option-codec.ts
  pnpm-lock.yaml
Labels: community

#2410 refactor(experimental): add getZeroableNullableCodec and getZeroableOptionCodec
  .changeset/thick-masks-lie.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/zeroable-nullable-test.ts
  packages/codecs-data-structures/src/__typetests__/bytes-typetest.ts
  packages/codecs-data-structures/src/__typetests__/zeroable-nullable-typetest.ts
  packages/codecs-data-structures/src/bytes.ts
  packages/codecs-data-structures/src/index.ts
  packages/codecs-data-structures/src/zeroable-nullable.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
  packages/options/README.md
  packages/options/package.json
  packages/options/src/__tests__/__setup__.ts
  packages/options/src/__tests__/zeroable-option-codec-test.ts
  packages/options/src/__typetests__/zeroable-option-codec-typetest.ts
  packages/options/src/option-codec.ts
  packages/options/src/zeroable-option-codec.ts
  packages/transactions/src/serializers/instruction.ts
  pnpm-lock.yaml
Labels: community

#2411 refactor(experimental): rename fixCodec and prefixCodec to fixCodecSize and prefixCodecSize
  .changeset/chatty-flies-end.md
  .changeset/shiny-birds-pay.md
  packages/addresses/src/__tests__/address-test.ts
  packages/codecs-core/README.md
  packages/codecs-core/src/__tests__/fix-codec-size-test.ts
  packages/codecs-core/src/__tests__/prefix-codec-size-test.ts
  packages/codecs-core/src/__tests__/reverse-codec-test.ts
  packages/codecs-core/src/__typetests__/fix-codec-size-typetest.ts
  packages/codecs-core/src/__typetests__/fix-codec-typetest.ts
  packages/codecs-core/src/__typetests__/prefix-codec-size-typetest.ts
  packages/codecs-core/src/__typetests__/prefix-codec-typetest.ts
  packages/codecs-core/src/fix-codec-size.ts
  packages/codecs-core/src/index.ts
  packages/codecs-core/src/prefix-codec-size.ts
  packages/codecs-data-structures/src/__tests__/bytes-test.ts
  packages/codecs-data-structures/src/__tests__/union-test.ts
  packages/codecs-data-structures/src/bytes.ts
  packages/codecs-data-structures/src/nullable.ts
  packages/codecs-strings/src/string.ts
  packages/options/src/option-codec.ts
  packages/rpc-api/src/__tests__/get-fee-for-message-test.ts
  packages/rpc-api/src/__tests__/send-transaction-test.ts
  packages/rpc-api/src/__tests__/simulate-transaction-test.ts
  packages/rpc-types/src/__tests__/blockhash-test.ts
Labels: community

#2412 refactor(experimental): remove the size option of getBytesCodec
  .changeset/silly-months-happen.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/bytes-test.ts
  packages/codecs-data-structures/src/__typetests__/bytes-typetest.ts
  packages/codecs-data-structures/src/bytes.ts
  packages/codecs-data-structures/src/zeroable-nullable.ts
  packages/options/src/zeroable-option-codec.ts
  packages/transactions/src/serializers/instruction.ts
  packages/transactions/src/serializers/transaction.ts
Labels: community

#2413 refactor(experimental): remove getStringCodec in favour of fixCodecSize and prefixCodecSize
  .changeset/late-planets-breathe.md
  packages/accounts/README.md
  packages/addresses/src/address.ts
  packages/codecs-core/README.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/array-test.ts
  packages/codecs-data-structures/src/__tests__/boolean-test.ts
  packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
  packages/codecs-data-structures/src/__tests__/map-test.ts
  packages/codecs-data-structures/src/__tests__/nullable-test.ts
  packages/codecs-data-structures/src/__tests__/set-test.ts
  packages/codecs-data-structures/src/__tests__/struct-test.ts
  packages/codecs-data-structures/src/__tests__/tuple-test.ts
  packages/codecs-data-structures/src/__typetests__/struct-typetest.ts
  packages/codecs-strings/README.md
  packages/codecs-strings/src/__tests__/string-test.ts
  packages/codecs-strings/src/__typetests__/string-typetest.ts
  packages/codecs-strings/src/index.ts
  packages/codecs-strings/src/string.ts
  packages/codecs-strings/src/utf8.ts
  packages/codecs/README.md
  packages/library/README.md
  packages/options/README.md
  packages/rpc-types/src/blockhash.ts
  packages/transactions/src/serializers/message.ts
Labels: community

#2414 refactor(experimental): nit: rename Endian enum variants
  .changeset/famous-buttons-switch.md
  packages/codecs-core/README.md
  packages/codecs-numbers/README.md
  packages/codecs-numbers/src/__tests__/f32-test.ts
  packages/codecs-numbers/src/__tests__/f64-test.ts
  packages/codecs-numbers/src/__tests__/i128-test.ts
  packages/codecs-numbers/src/__tests__/i16-test.ts
  packages/codecs-numbers/src/__tests__/i32-test.ts
  packages/codecs-numbers/src/__tests__/i64-test.ts
  packages/codecs-numbers/src/__tests__/u128-test.ts
  packages/codecs-numbers/src/__tests__/u16-test.ts
  packages/codecs-numbers/src/__tests__/u32-test.ts
  packages/codecs-numbers/src/__tests__/u64-test.ts
  packages/codecs-numbers/src/common.ts
  packages/codecs-numbers/src/utils.ts
Labels: community

#2417 refactor(experimental): rename prefixCodecSize to addCodecSizePrefix
  .changeset/chatty-flies-end.md
  .changeset/late-planets-breathe.md
  .changeset/silly-months-happen.md
  packages/accounts/README.md
  packages/codecs-core/README.md
  packages/codecs-core/src/__tests__/add-codec-size-prefix-test.ts
  packages/codecs-core/src/__typetests__/add-codec-size-prefix-typetest.ts
  packages/codecs-core/src/__typetests__/prefix-codec-size-typetest.ts
  packages/codecs-core/src/add-codec-size-prefix.ts
  packages/codecs-core/src/index.ts
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/array-test.ts
  packages/codecs-data-structures/src/__tests__/bytes-test.ts
  packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
  packages/codecs-data-structures/src/__tests__/map-test.ts
  packages/codecs-data-structures/src/__tests__/nullable-test.ts
  packages/codecs-data-structures/src/__tests__/set-test.ts
  packages/codecs-data-structures/src/__tests__/struct-test.ts
  packages/codecs-data-structures/src/__tests__/tuple-test.ts
  packages/codecs-data-structures/src/bytes.ts
  packages/codecs-strings/README.md
  packages/codecs-strings/src/__tests__/string-test.ts
  packages/codecs/README.md
  packages/library/README.md
  packages/options/README.md
  packages/transactions/src/serializers/instruction.ts
Labels: community

#2512 Add glyphs to fix Hash collision with bigint and string
  packages/fast-stable-stringify/src/__tests__/index-test.ts
  packages/fast-stable-stringify/src/index.ts
Labels: community

#2552 [refactor] [experimental] Use optimised base16 encode strategy
  packages/codecs-strings/src/__benchmarks__/run.ts
  packages/codecs-strings/src/base16.ts
Labels: automerge, community

#2576 Enforce TypeScript >=5 via `peerDependencies`
  packages/accounts/package.json
  packages/addresses/package.json
  packages/assertions/package.json
  packages/codecs-core/package.json
  packages/codecs-data-structures/package.json
  packages/codecs-numbers/package.json
  packages/codecs-strings/package.json
  packages/codecs/package.json
  packages/compat/package.json
  packages/errors/package.json
  packages/fast-stable-stringify/package.json
  packages/functional/package.json
  packages/instructions/package.json
  packages/keys/package.json
  packages/library/package.json
  packages/options/package.json
  packages/programs/package.json
  packages/rpc-api/package.json
  packages/rpc-graphql/package.json
  packages/rpc-parsed-types/package.json
  packages/rpc-spec-types/package.json
  packages/rpc-spec/package.json
  packages/rpc-subscriptions-api/package.json
  packages/rpc-subscriptions-spec/package.json
  packages/rpc-subscriptions-transport-websocket/package.json
  packages/rpc-subscriptions/package.json
  packages/rpc-transformers/package.json
  packages/rpc-transport-http/package.json
  packages/rpc-types/package.json
  packages/rpc/package.json
  packages/signers/package.json
  packages/sysvars/package.json
  packages/transaction-confirmation/package.json
  packages/transaction-messages/package.json
  packages/transactions/package.json
  packages/webcrypto-ed25519-polyfill/package.json
  pnpm-lock.yaml
Labels: automerge

#2575 graphql: token-2022 extensions: InitializeTransferFeeConfig
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2583 chore: fix some typos in comments
  packages/codecs-core/src/__tests__/add-codec-sentinel-test.ts
  packages/codecs-data-structures/README.md
  packages/errors/src/context.ts
  packages/rpc-types/src/typed-numbers.ts
  packages/transaction-confirmation/src/confirmation-strategy-blockheight.ts
Labels: community
