Repository solana-labs/solana-web3.js, pull requests merged in 2024-03, with the labels that each got.

#2229 Upgrade `mock-socket` to 9.3.1 and reenable test
  package.json
  packages/rpc-subscriptions-transport-websocket/src/__tests__/websocket-connection-test.ts
  pnpm-lock.yaml
Labels: automerge

#2238 refactor(experimental): add function to create a Solana RPC using only an URL
  packages/rpc/src/__tests__/rpc-integer-overflow-test.ts
  packages/rpc/src/__typetests__/rpc-clusters-typetest.ts
  packages/rpc/src/rpc-transport.ts
  packages/rpc/src/rpc.ts
Labels: community

#2239 refactor(experimental): add function to create Solana RPC Subscriptions using only an URL
  packages/rpc-subscriptions/src/__typetests__/rpc-subscriptions-clusters-typetest.ts
  packages/rpc-subscriptions/src/rpc-subscriptions-transport.ts
  packages/rpc-subscriptions/src/rpc-subscriptions.ts
Labels: community

#2249 refactor(experimental): add guidelines to error codes
  packages/errors/src/codes.ts
Labels: community

#2250 refactor(experimental): group Subtle Crypto errors
  packages/errors/src/codes.ts
Labels: community

#2251 refactor(experimental): group Instruction errors
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
  packages/instructions/src/instruction.ts
Labels: community

#2252 refactor(experimental): group RPC errors
  packages/errors/src/codes.ts
Labels: community

#2253 refactor(experimental): move Invariant errors range to the end
  packages/errors/src/codes.ts
Labels: community

#2254 refactor(experimental): group Address errors
  packages/errors/src/codes.ts
Labels: community

#2255 refactor(experimental): group Account errors
  packages/errors/src/codes.ts
Labels: community

#2256 refactor(experimental): move and rename INVALID_KEYPAIR_BYTES error
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
  packages/keys/src/key-pair.ts
Labels: community

#2257 refactor(experimental): rename ungrouped and addresses errors
  packages/addresses/src/__tests__/address-test.ts
  packages/addresses/src/__tests__/coercions-test.ts
  packages/addresses/src/__tests__/program-derived-address-test.ts
  packages/addresses/src/address.ts
  packages/addresses/src/program-derived-address.ts
  packages/addresses/src/public-key.ts
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
  packages/rpc-types/src/__tests__/blockhash-test.ts
  packages/rpc-types/src/blockhash.ts
  packages/transaction-confirmation/src/__tests__/confirmation-strategy-nonce-test.ts
  packages/transaction-confirmation/src/confirmation-strategy-nonce.ts
Labels: community

#2259 refactor(experimental): rename accounts errors
  packages/accounts/src/__tests__/decode-account-test.ts
  packages/accounts/src/__tests__/maybe-account-test.ts
  packages/accounts/src/decode-account.ts
  packages/accounts/src/maybe-account.ts
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2260 refactor(experimental): rename Subtle Crypto errors
  packages/assertions/src/__tests__/subtle-crypto-test.ts
  packages/assertions/src/subtle-crypto.ts
  packages/errors/src/codes.ts
  packages/errors/src/messages.ts
Labels: community

#2261 refactor(experimental): rename transaction errors
  packages/compat/src/__tests__/transaction-test.ts
  packages/compat/src/transaction.ts
  packages/errors/README.md
  packages/errors/src/__typetests__/error-typetest.ts
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
  packages/signers/src/__tests__/sign-transaction-test.ts
  packages/transaction-confirmation/src/__tests__/waiters-test.ts
  packages/transactions/src/__tests__/signatures-test.ts
  packages/transactions/src/signatures.ts
Labels: community

#2262 refactor(experimental): rename codec errors
  packages/addresses/src/__tests__/address-test.ts
  packages/codecs-core/src/__tests__/combine-codec.ts
  packages/codecs-core/src/__tests__/fix-codec-test.ts
  packages/codecs-core/src/__tests__/reverse-codec-test.ts
  packages/codecs-core/src/assertions.ts
  packages/codecs-core/src/codec.ts
  packages/codecs-core/src/combine-codec.ts
  packages/codecs-data-structures/src/__tests__/array-test.ts
  packages/codecs-data-structures/src/__tests__/bit-array-test.ts
  packages/codecs-data-structures/src/__tests__/boolean-test.ts
  packages/codecs-data-structures/src/__tests__/bytes-test.ts
  packages/codecs-data-structures/src/__tests__/map-test.ts
  packages/codecs-data-structures/src/__tests__/nullable-test.ts
  packages/codecs-data-structures/src/__tests__/set-test.ts
  packages/codecs-data-structures/src/__tests__/tuple-test.ts
  packages/codecs-data-structures/src/assertions.ts
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2263 refactor(experimental): rename RPC errors
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
  packages/rpc-transport-http/src/__tests__/http-transport-headers-test.ts
  packages/rpc-transport-http/src/http-transport-headers.ts
Labels: community

#2265 refactor(experimental): fix linting errors
  packages/accounts/src/__tests__/decode-account-test.ts
  packages/accounts/src/decode-account.ts
  packages/addresses/src/program-derived-address.ts
  packages/assertions/src/__tests__/subtle-crypto-test.ts
  packages/assertions/src/subtle-crypto.ts
  packages/codecs-core/src/combine-codec.ts
  packages/compat/src/transaction.ts
  packages/rpc-types/src/__tests__/blockhash-test.ts
  packages/rpc-types/src/blockhash.ts
  packages/transaction-confirmation/src/__tests__/confirmation-strategy-nonce-test.ts
  packages/transaction-confirmation/src/confirmation-strategy-nonce.ts
  packages/transactions/src/__tests__/signatures-test.ts
  packages/transactions/src/signatures.ts
Labels: community

#2266 refactor(experimental): fix error code increments within each group
  packages/errors/src/codes.ts
Labels: community

#2258 [vote-program] adding instruction update validator identity
  packages/library-legacy/src/programs/vote.ts
Labels: community

#2285 `pnpm dev` was broken because I removed these packages
  package.json
  pnpm-lock.yaml
Labels: automerge

#2287 refactor(experimental): Fix codecs-data-structure documentation
  packages/codecs-data-structures/README.md
Labels: community

#2298 Distribute only the types package of `undici` with `@solana/rpc-transport-http`
  packages/rpc-transport-http/package.json
  packages/rpc-transport-http/src/http-transport.ts
  pnpm-lock.yaml
Labels: automerge

#2293 refactor(experimental): add resizeCodec helper to @solana/codecs-core
  packages/codecs-core/README.md
  packages/codecs-core/src/__tests__/resize-codec-test.ts
  packages/codecs-core/src/__typetests__/resize-codec-typetest.ts
  packages/codecs-core/src/index.ts
  packages/codecs-core/src/resize-codec.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2314 refactor(experimental): add padLeftCodec and padRightCodec helpers to @solana/codecs-core
  packages/codecs-core/README.md
  packages/codecs-core/src/__tests__/__setup__.ts
  packages/codecs-core/src/__tests__/offset-codec-test.ts
  packages/codecs-core/src/__tests__/pad-codec-test.ts
  packages/codecs-core/src/__typetests__/pad-codec-typetest.ts
  packages/codecs-core/src/pad-codec.ts
  packages/codecs/README.md
Labels: community

#2299 refactor(experimental): add blockhash codec and type assertions
  packages/rpc-types/src/__tests__/blockhash-test.ts
  packages/rpc-types/src/blockhash.ts
Labels: community

#2318 refactor(experimental): add lamports codec
  packages/rpc-types/package.json
  packages/rpc-types/src/__tests__/lamports-test.ts
  packages/rpc-types/src/lamports.ts
  pnpm-lock.yaml
Labels: community

#2300 refactor(experimental): init sysvars package
  packages/sysvars/.gitignore
  packages/sysvars/.npmrc
  packages/sysvars/.prettierignore
  packages/sysvars/LICENSE
  packages/sysvars/README.md
  packages/sysvars/package.json
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/index.ts
  packages/sysvars/tsconfig.declarations.json
  packages/sysvars/tsconfig.json
  pnpm-lock.yaml
Labels: community

#2301 refactor(experimental): sysvars package: clock
  packages/sysvars/package.json
  packages/sysvars/src/__tests__/__setup__.ts
  packages/sysvars/src/__tests__/clock-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/clock.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/sysvar.ts
  pnpm-lock.yaml
Labels: community

#2302 refactor(experimental): sysvars package: epoch rewards
  packages/sysvars/src/__tests__/epoch-rewards-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/epoch-rewards.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2303 refactor(experimental): sysvars package: epoch schedule
  packages/sysvars/src/__tests__/epoch-schedule-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/epoch-schedule.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2304 refactor(experimental): sysvars package: fees
  packages/sysvars/src/__tests__/fees-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/fees.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2305 refactor(experimental): sysvars package: instructions
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2306 refactor(experimental): sysvars package: last restart slot
  packages/sysvars/src/__tests__/last-restart-slot-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/last-restart-slot.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2307 refactor(experimental): sysvars package: recent blockhashes
  packages/sysvars/src/__tests__/recent-blockhashes-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/recent-blockhashes.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2308 refactor(experimental): sysvars package: rent
  packages/sysvars/src/__tests__/rent-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/rent.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2309 refactor(experimental): sysvars package: slot hashes
  packages/sysvars/src/__tests__/slot-hashes-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/slot-hashes.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2310 refactor(experimental): sysvars package: slot history
  packages/sysvars/package.json
  packages/sysvars/src/__tests__/slot-history-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/slot-history.ts
  packages/sysvars/src/sysvar.ts
  pnpm-lock.yaml
Labels: community

#2311 refactor(experimental): sysvars package: stake history
  packages/sysvars/src/__tests__/stake-history-test.ts
  packages/sysvars/src/__tests__/sysvar-test.ts
  packages/sysvars/src/__typetests__/sysvar-typetest.ts
  packages/sysvars/src/index.ts
  packages/sysvars/src/stake-history.ts
  packages/sysvars/src/sysvar.ts
Labels: community

#2317 refactor(experimental): update program client documentation in library README
  packages/library/README.md
Labels: community

#2323 refactor(experimental): export missing pad-codec file
  packages/codecs-core/src/index.ts
Labels: community

#2316 refactor(experimental): graphql: update documentation
  packages/library/README.md
  packages/rpc-graphql/README.md
Labels: community

#2326 Fix a bug in Node <21 that prevented the normal operation of the request coalescer
  packages/rpc/src/rpc-request-coalescer.ts
Labels: automerge

#2332 chore: fix typos
  packages/rpc-graphql/README.md
  packages/rpc-subscriptions-transport-websocket/src/__tests__/websocket-connection-test.ts
Labels: automerge, community

#2333 Upgrade Turborepo to `v.1.12.5`
  package.json
  pnpm-lock.yaml
Labels: automerge

#2321 refactor(experimental): add tests for offsetted array codecs
  packages/codecs-data-structures/src/__tests__/array-test.ts
Labels: community

#2330 add installing node modules section in README.md
  README.md
Labels: community

#2340 refactor(experimental): sysvars: documentation
  packages/sysvars/README.md
Labels: community

#2334 refactor(experimental): update preview tag in library README
  packages/library/README.md
Labels: community

#2335 refactor(experimental): update package list in library README
  packages/library/README.md
Labels: community

#2336 refactor(experimental): update RPC documentation in library README
  packages/library/README.md
Labels: community

#2338 refactor(experimental): fix codecs documentation URL in library README
  packages/library/README.md
Labels: community

#2322 refactor(experimental): use DrainOuterGeneric helper on codec type mappings
  .changeset/heavy-students-relax.md
  packages/codecs-data-structures/src/data-enum.ts
  packages/codecs-data-structures/src/struct.ts
  packages/codecs-data-structures/src/utils.ts
Labels: community

#2344 refactor(experimental): improve getTupleCodec type inferences
  .changeset/green-experts-hang.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/tuple-test.ts
  packages/codecs-data-structures/src/__typetests__/tuple-typetest.ts
  packages/codecs-data-structures/src/map.ts
  packages/codecs-data-structures/src/tuple.ts
Labels: community

#2376 Negative error codes now get decoded correctly by the production error decoder
  .changeset/breezy-items-reflect.md
  packages/errors/README.md
  packages/errors/src/__tests__/message-formatter-test.ts
  packages/errors/src/message-formatter.ts
Labels: automerge

#2329 [experimental] Validate that the public key generated from createKeyPairFromBytes() belongs to the private key
  .changeset/thick-radios-search.md
  packages/assertions/src/__tests__/crypto-test.ts
  packages/assertions/src/crypto.ts
  packages/assertions/src/index.ts
  packages/errors/src/codes.ts
  packages/errors/src/messages.ts
  packages/keys/src/__tests__/key-pair-test.ts
  packages/keys/src/key-pair.ts
Labels: community

#2385 Revert "Show no Turbo logs except when there is an error (#2366)"
  turbo.json
Labels: automerge

#1914 Upgrade to Jest 30
  package.json
  packages/addresses/src/__tests__/address-test.ts
  packages/assertions/src/__tests__/subtle-crypto-test.ts
  packages/rpc-graphql/src/loaders/__tests__/account-loader-test.ts
  packages/rpc-graphql/src/loaders/__tests__/block-loader-test.ts
  packages/rpc-graphql/src/loaders/__tests__/program-accounts-loader-test.ts
  packages/rpc-graphql/src/loaders/__tests__/transaction-loader-test.ts
  packages/rpc-graphql/src/resolvers/__tests__/account-resolver-test.ts
  packages/rpc-graphql/src/resolvers/__tests__/block-resolver-test.ts
  packages/rpc-graphql/src/resolvers/__tests__/program-accounts-resolver-test.ts
  packages/rpc-graphql/src/resolvers/__tests__/transaction-resolver-test.ts
  packages/rpc-subscriptions/src/__tests__/cached-abortable-iterable-test.ts
  packages/rpc-transport-http/src/__tests__/http-transport-headers-test.ts
  packages/rpc-transport-http/src/__tests__/http-transport-test.ts
  packages/rpc-types/src/__tests__/blockhash-test.ts
  pnpm-lock.yaml
Labels: do-not-close

#2386 Move comments about signature busting to the callsites that bust the signatures
  packages/signers/src/fee-payer-signer.ts
  packages/transactions/src/blockhash.ts
  packages/transactions/src/durable-nonce.ts
  packages/transactions/src/fee-payer.ts
  packages/transactions/src/instructions.ts
  packages/transactions/src/unsigned-transaction.ts
Labels: automerge

#2380 refactor(experimental): support custom discriminator property for getDataEnumCodec
  .changeset/violet-brooms-report.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/data-enum-test.ts
  packages/codecs-data-structures/src/__typetests__/data-enum-typetest.ts
  packages/codecs-data-structures/src/data-enum.ts
Labels: community

#2382 refactor(experimental): rename getDataEnumCodec to getDiscriminatedUnionCodec
  .changeset/odd-beds-punch.md
  packages/codecs-core/README.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/discriminated-union-test.ts
  packages/codecs-data-structures/src/__typetests__/discriminated-union-typetest.ts
  packages/codecs-data-structures/src/discriminated-union.ts
  packages/codecs-data-structures/src/index.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2383 refactor(experimental): rename getScalarEnumCodec to getEnumCodec
  .changeset/loud-otters-pull.md
  packages/codecs-core/README.md
  packages/codecs-data-structures/README.md
  packages/codecs-data-structures/src/__tests__/enum-test.ts
  packages/codecs-data-structures/src/__tests__/scalar-enum-test.ts
  packages/codecs-data-structures/src/__typetests__/enum-typetest.ts
  packages/codecs-data-structures/src/__typetests__/scalar-enum-typetest.ts
  packages/codecs-data-structures/src/enum.ts
  packages/codecs-data-structures/src/index.ts
  packages/codecs-data-structures/src/scalar-enum.ts
  packages/codecs/README.md
  packages/errors/src/codes.ts
  packages/errors/src/context.ts
  packages/errors/src/messages.ts
Labels: community

#2384 refactor(experimental): nit: rename define to describe
  packages/rpc-subscriptions/src/__typetests__/rpc-subscriptions-clusters-typetest.ts
  packages/rpc/src/__typetests__/rpc-clusters-typetest.ts
Labels: community
