Repository solana-labs/solana-web3.js, pull requests merged in 2024-05, with the labels that each got.

#2609 Apply default input dependencies to every Turbo step
  turbo.json
Labels: automerge

#2608 refactor(experimental): graphql: token-2022 extensions: harvestWithheldTokensToMint and WithdrawWithheldTokensFromAccounts
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2579 refactor(experimental): graphql: token-2022 extensions: withdrawWithheldTokensFromMint
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2578 refactor(experimental): graphql: token-2022 extensions: TransferCheckedWithFee
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2617 refactor(experimental): graphql: token-2022 extensions: RequiredMemoTransfers
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2620 refactor(experimental): graphql: token-2022 extensions: InitializeConfidentialTransferMint
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2618 refactor(experimental): graphql: token-2022 extensions: InitializeInterestBearingConfig, UpdateInterestBearingConfig
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2621 refactor(experimental): graphql: token-2022 extensions: ApproveConfidentialTransferAccount, EmptyConfidentialTransferAccount
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2623 refactor(experimental): graphql: token-2022 extensions: ConfigureConfidentialTransferAccount Instruction #2611
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2636 refactor(experimental): graphql: token-2022 extensions: ApplyPendingConfidentialTransferBalance
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2650 refactor(experimental): graphql: token-2022 extensions: EnableConfidentialTransferNonConfidentialCredits DisableConfidentialTransferNonConfidentialCredits
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: automerge, community

#2652 refactor(experimental): graphql: token-2022 extensions: DepositConfidentialTransfer
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2653 refactor(experimental): graphql: token-2022 extensions: WithdrawConfidentialTransfer
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2654 refactor(experimental): graphql: token-2022 extensions: ConfidentialTransfer
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2655 refactor(experimental): graphql: token-2022 extensions: ConfidentialTransferWithSplitProofs
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2656 refactor(experimental): graphql: token-2022 extensions: UpdateConfidentialTransferMint
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2662 refactor(experimental): graphql: token-2022 extensions: WithdrawWithheldConfidentialTransferTokensFromMint
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: automerge, community

#2675 refactor(experimental): graphql: token-2022 extensions: WithdrawWithheldConfidentialTransferTokensFromFromAccounts
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: automerge, community

#2679 refactor(experimental): graphql: token-2022 extensions: HarvestWithheldConfidentialTransferTokensToMint
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: automerge, community

#2680 refactor(experimental): graphql: token-2022 extensions: EnableConfidentialTransferFeeHarvestToMint DisableConfidentialTransferFeeHarvestToMint
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2682 refactor(experimental): graphql: token-2022 extensions: InitializeConfidentialTransferFeeConfig
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2687 refactor(experimental): graphql: token-2022 extensions: InitializeTokenGroup
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2688 refactor(experimental): graphql: token-2022 extensions: UpdateGroupMaxSize
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2690 refactor(experimental): graphql: token-2022 extensions: UpdateGroupAuthority
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2691 refactor(experimental): graphql: token-2022 extensions: InitializeTokenGroupMember
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: automerge, community

#2692 refactor(experimental): graphql: token-2022 extensions: InitializeMetadata
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2693 refactor(experimental): graphql: token-2022 extensions: UpdateField
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: automerge, community

#2694 refactor(experimental): graphql: token-2022 extensions: RemoveKey
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2699 refactor(experimental): graphql: token-2022 extensions account state: confidentialTransferAccount
  packages/rpc-graphql/src/__tests__/account-test.ts
  packages/rpc-graphql/src/resolvers/account.ts
  packages/rpc-graphql/src/schema/account.ts
Labels: community

#2697 Support SPL Token account state within the schema for Token Account
  packages/rpc-graphql/src/__tests__/account-test.ts
  packages/rpc-graphql/src/resolvers/account.ts
  packages/rpc-graphql/src/schema/account.ts
Labels: community

#2700 refactor(experimental): graphql: token-2022 extensions: UpdateAuthority Emit
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2717 Migrate to Agave test validator
  .github/workflows/actions/setup-validator/action.yml
  .gitignore
  scripts/get-latest-validator-release-version.sh
  scripts/setup-test-validator.sh
  scripts/start-shared-test-validator.sh
Labels: automerge

#2719 Repair tests after #2717
  packages/library-legacy/src/utils/makeWebsocketUrl.ts
  packages/rpc-api/src/__tests__/get-cluster-nodes-test.ts
  packages/rpc-api/src/__tests__/get-version-test.ts
Labels: automerge

#2729 Repair the type of `getProgramAccounts` with respect to the `memcmp` filter
  packages/rpc-subscriptions-api/src/__typetests__/program-notifications-type-test.ts
  packages/rpc-subscriptions-api/src/program-notifications.ts
Labels: automerge

#2734 Pull in `ReadonlyUint8Array` as a type
  packages/compat/src/transaction.ts
  packages/signers/src/__tests__/sign-transaction-test.ts
  packages/signers/src/keypair-signer.ts
  packages/transaction-confirmation/src/__tests__/waiters-test.ts
Labels: automerge

#2737 Import `ReadonlyUint8Array` from `@solana/codecs-core` wherever necessary
  packages/compat/package.json
  packages/compat/src/transaction.ts
  packages/signers/package.json
  packages/signers/src/__tests__/sign-transaction-test.ts
  packages/signers/src/keypair-signer.ts
  packages/transaction-confirmation/package.json
  packages/transaction-confirmation/src/__tests__/waiters-test.ts
  pnpm-lock.yaml
Labels: automerge

#2739 Turbocharge the `reverseCodec()`
  packages/codecs-core/package.json
  packages/codecs-core/src/__benchmarks__/run.ts
  packages/codecs-core/src/__tests__/reverse-codec-test.ts
  packages/codecs-core/src/reverse-codec.ts
  pnpm-lock.yaml
Labels: automerge
