Repository solana-labs/solana-web3.js, pull requests merged in 2024-10, with the labels that each got.

#3329 chore: eliminate old version of Rollup
  package.json
  pnpm-lock.yaml
Labels: automerge, 1.x

#3331 Update semver past 5.7.1
  pnpm-lock.yaml
Labels: automerge

#3332 chore: update ws past 8.17.0
  pnpm-lock.yaml
Labels: automerge

#3333 Update dset past 3.1.3
  package.json
  pnpm-lock.yaml
Labels: automerge

#3337 Update past `axios` 1.7.3
  pnpm-lock.yaml
Labels: automerge

#3334 Update past `ws` 8.17.0
  pnpm-lock.yaml
Labels: automerge

#3335 Update past `micromatch` 4.0.7
  pnpm-lock.yaml
Labels: automerge

#3336 Update past `rollup` 4.22.3
  pnpm-lock.yaml
Labels: automerge

#3339 Update `rollup` to 4.24.0
  pnpm-lock.yaml
Labels: automerge

#3340 The default RPC transport now requests wire compression in Node
  .changeset/six-olives-hang.md
  packages/rpc-transport-http/src/__tests__/http-transport-headers-test.ts
  packages/rpc-transport-http/src/http-transport-headers.ts
  packages/rpc/src/__tests__/rpc-transport-header-config-test.ts
  packages/rpc/src/rpc-transport.ts
Labels: automerge

#3347 Repair benchmarks
  packages/build-scripts/package.json
  packages/build-scripts/register-node-globals.cjs
  packages/codecs-core/src/__benchmarks__/run.ts
  packages/codecs-strings/src/__benchmarks__/run.ts
  packages/fetch-impl/src/__benchmarks__/run.ts
  packages/keys/src/__benchmarks__/run.ts
  packages/rpc-transport-http/src/__benchmarks__/run.ts
Labels: automerge

#3392 fix: cover logs error for ws message
  src/connection.ts
Labels: community

#3462 Make React context in the example app work with hot module replacement
  examples/react-app/src/context/ChainContext.tsx
  examples/react-app/src/context/ChainContextProvider.tsx
  examples/react-app/src/context/RpcContext.tsx
  examples/react-app/src/context/RpcContextProvider.tsx
  examples/react-app/src/context/SelectedWalletAccountContext.tsx
  examples/react-app/src/context/SelectedWalletAccountContextProvider.tsx
  examples/react-app/src/main.tsx
Labels: automerge
