Repository solana-labs/solana-web3.js, pull requests merged in 2024-06, with the labels that each got.

#2736 Added transaction logs to send transaction functions
  .changeset/stupid-trees-exist.md
  packages/library-legacy/src/connection.ts
  packages/library-legacy/src/errors.ts
  packages/library-legacy/src/utils/send-and-confirm-raw-transaction.ts
  packages/library-legacy/src/utils/send-and-confirm-transaction.ts
  packages/library-legacy/test/connection.test.ts
Labels: community

#2765 chore: Fixed sendTransactionError types
  packages/library-legacy/src/connection.ts
  packages/library-legacy/src/errors.ts
  packages/library-legacy/src/utils/send-and-confirm-raw-transaction.ts
  packages/library-legacy/src/utils/send-and-confirm-transaction.ts
Labels: automerge, community

#2769 chore: rename transactionLogs back to logs
  packages/library-legacy/src/connection.ts
  packages/library-legacy/src/errors.ts
Labels: community

#2771 chore: Add getter for logs to sendTransactionError
  packages/library-legacy/src/errors.ts
Labels: automerge, community

#2785 fix: Rewrite the message printer as a parser to avoid problems with regexes in old browsers
  .changeset/proud-poems-try.md
  packages/errors/src/__tests__/message-formatter-test.ts
  packages/errors/src/message-formatter.ts
Labels: automerge

#2641 refactor(experimental): graphql: group schema typedefs
  packages/rpc-graphql/src/index.ts
  packages/rpc-graphql/src/schema/type-defs/account.ts
  packages/rpc-graphql/src/schema/type-defs/block.ts
  packages/rpc-graphql/src/schema/type-defs/index.ts
  packages/rpc-graphql/src/schema/type-defs/instruction.ts
  packages/rpc-graphql/src/schema/type-defs/root.ts
  packages/rpc-graphql/src/schema/type-defs/transaction.ts
  packages/rpc-graphql/src/schema/type-defs/types.ts
Labels: do-not-close

#2642 refactor(experimental): graphql: group schema type resolvers
  packages/rpc-graphql/src/index.ts
  packages/rpc-graphql/src/resolvers/account.ts
  packages/rpc-graphql/src/resolvers/block.ts
  packages/rpc-graphql/src/resolvers/index.ts
  packages/rpc-graphql/src/resolvers/root.ts
  packages/rpc-graphql/src/resolvers/transaction.ts
  packages/rpc-graphql/src/schema/type-resolvers/account.ts
  packages/rpc-graphql/src/schema/type-resolvers/block.ts
  packages/rpc-graphql/src/schema/type-resolvers/index.ts
  packages/rpc-graphql/src/schema/type-resolvers/instruction.ts
  packages/rpc-graphql/src/schema/type-resolvers/root.ts
  packages/rpc-graphql/src/schema/type-resolvers/transaction.ts
  packages/rpc-graphql/src/schema/type-resolvers/types.ts
Labels: do-not-close

#2845 chore: fix some comments
  packages/library/README.md
  packages/library/src/compute-limit-internal.ts
Labels: community

#2858 Add `minContextSlot` as an option to `Transaction{Sending}SignerConfig`
  .changeset/wicked-cougars-matter.md
  packages/react/src/__tests__/useWalletAccountTransactionSendingSigner-test.ts
  packages/react/src/__tests__/useWalletAccountTransactionSigner-test.ts
  packages/react/src/useWalletAccountTransactionSendingSigner.ts
  packages/react/src/useWalletAccountTransactionSigner.ts
  packages/signers/src/__tests__/sign-transaction-test.ts
  packages/signers/src/sign-transaction.ts
  packages/signers/src/transaction-modifying-signer.ts
  packages/signers/src/transaction-partial-signer.ts
  packages/signers/src/transaction-sending-signer.ts
  packages/signers/src/types.ts
Labels: automerge

#2860 Rehabilitate the fetch benchmark
  packages/fetch-impl/LICENSE
  packages/fetch-impl/package.json
  packages/fetch-impl/src/__benchmarks__/run.ts
  packages/fetch-impl/tsconfig.json
  pnpm-lock.yaml
Labels: automerge

#2756 feat(simulated_transaction): Add Inner Instructions
  packages/library-legacy/src/connection.ts
Labels: automerge, community
