Repository solana-labs/solana-web3.js, pull requests merged in 2024-07, with the labels that each got.

#2919 feat: add `iconUrl` to `ValidatorInfo` type
  packages/library-legacy/src/validator-info.ts
  packages/library-legacy/test/validator-info.test.ts
Labels: community

#2957 Use non-animated Jest output when running in the context of Turborepo
  examples/react-app/package.json
  packages/accounts/package.json
  packages/addresses/package.json
  packages/assertions/package.json
  packages/codecs-core/package.json
  packages/codecs-data-structures/package.json
  packages/codecs-numbers/package.json
  packages/codecs-strings/package.json
  packages/codecs/package.json
  packages/compat/package.json
  packages/crypto-impl/package.json
  packages/errors/package.json
  packages/fast-stable-stringify/package.json
  packages/functional/package.json
  packages/instructions/package.json
  packages/keys/package.json
  packages/library/package.json
  packages/options/package.json
  packages/programs/package.json
  packages/react/package.json
  packages/rpc-api/package.json
  packages/rpc-graphql/package.json
  packages/rpc-parsed-types/package.json
  packages/rpc-spec-types/package.json
  packages/rpc-spec/package.json
  packages/rpc-subscriptions-api/package.json
  packages/rpc-subscriptions-spec/package.json
  packages/rpc-subscriptions-transport-websocket/package.json
  packages/rpc-subscriptions/package.json
  packages/rpc-transformers/package.json
  packages/rpc-transport-http/package.json
  packages/rpc-types/package.json
  packages/rpc/package.json
  packages/signers/package.json
  packages/sysvars/package.json
  packages/text-encoding-impl/package.json
  packages/transaction-confirmation/package.json
  packages/transaction-messages/package.json
  packages/transactions/package.json
  packages/webcrypto-ed25519-polyfill/package.json
  packages/ws-impl/package.json
Labels: automerge

#2960 An example of how to use the new `@solana/web3.js` to transfer Lamports from one account to another
  examples/transfer-lamports/package.json
  examples/transfer-lamports/src/example.ts
  examples/transfer-lamports/tsconfig.json
  examples/utils/.gitignore
  examples/utils/.prettierignore
  examples/utils/LICENSE
  examples/utils/createLogger.ts
  examples/utils/package.json
  examples/utils/pressAnyKeyPrompt.ts
  examples/utils/tsconfig.declarations.json
  examples/utils/tsconfig.json
  pnpm-lock.yaml
  scripts/fixtures/example-transfer-lamports-source-account.json
Labels: automerge

#2962 Update Turborepo to 2.0.9
  package.json
  pnpm-lock.yaml
Labels: automerge

#2910 The RPC request coalescer now throws exceptions whether you configure it with an `AbortSignal` or not
  .changeset/chilled-walls-scream.md
  packages/rpc/src/__tests__/rpc-request-coalescer-test.ts
  packages/rpc/src/rpc-request-coalescer.ts
Labels: automerge, community, stale

#2992 fix: correct import for `getSetComputeUnitLimitInstruction` helper
  packages/library/README.md
Labels: community

#3009 chore: make legacy connection tests resilient to the validator having just been spun up
  packages/library-legacy/test/connection.test.ts
Labels: automerge
