Repository solana-labs/solana-web3.js, pull requests merged in 2024-01, with the labels that each got.

#1988 Update encoding in the transaction config
  packages/rpc-graphql/src/loaders/transaction.ts
Labels: community

#1978 refactor(experimental): add programs package
  packages/programs/.gitignore
  packages/programs/.prettierignore
  packages/programs/LICENSE
  packages/programs/README.md
  packages/programs/package.json
  packages/programs/src/__tests__/resolve-transaction-error-test.ts
  packages/programs/src/index.ts
  packages/programs/src/program.ts
  packages/programs/src/resolve-transaction-error.ts
  packages/programs/src/types/global.d.ts
  packages/programs/tsconfig.declarations.json
  packages/programs/tsconfig.json
  pnpm-lock.yaml
Labels: community

#2002 feat: specify which account is missing/has an invalid signature on signature verification failure
  packages/library-legacy/src/transaction/legacy.ts
  packages/library-legacy/test/transaction.test.ts
Labels: automerge, community

#1970 refactor(experimental): use scoped APIs in rpc-core tests
  packages/rpc-core/src/rpc-methods/__tests__/get-account-info-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-balance-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-block-height.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-block-production-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-block-time-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-cluster-nodes-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-epoch-info-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-epoch-schedule-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-fee-for-message-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-first-available-block-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-genesis-hash-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-health-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-identity-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-inflation-governor-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-inflation-rate-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-inflation-reward-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-largest-accounts-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-latest-blockhash-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-leader-schedule-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-max-retransmit-slot-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-max-shred-insert-slot-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-minimum-balance-for-rent-exemption-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-multiple-accounts-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-program-accounts-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-recent-prioritization-fees-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-signature-statuses-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-signatures-for-address-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-slot-leader-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-slot-leaders-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-slot-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-stake-activation-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-stake-minimum-delegation-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-supply-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-token-account-balance-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-token-accounts-by-delegate-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-token-accounts-by-owner-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-token-largest-accounts-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-token-supply-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-transaction-count-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-transaction-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-version-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/get-vote-accounts.ts
  packages/rpc-core/src/rpc-methods/__tests__/is-blockhash-valid-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/minimum-ledger-slot-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/request-airdrop-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/send-transaction-test.ts
  packages/rpc-core/src/rpc-methods/__tests__/simulate-transaction-test.ts
  packages/rpc-core/src/rpc-methods/__typetests__/get-block-type-test.ts
  packages/rpc-core/src/rpc-methods/index.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/slot-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/slots-updates-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/__tests__/vote-notifications-test.ts
  packages/rpc-core/src/rpc-subscriptions/index.ts
Labels: community, stale

#1971 refactor(experimental): use scoped APIs in rpc-graphql tests
  packages/rpc-graphql/src/__tests__/account-test.ts
  packages/rpc-graphql/src/__tests__/block-tests.ts
  packages/rpc-graphql/src/__tests__/program-accounts-test.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
Labels: community, stale

#1972 refactor(experimental): use scoped APIs in rpc-graphql
  packages/rpc-graphql/src/loaders/account.ts
  packages/rpc-graphql/src/loaders/block.ts
  packages/rpc-graphql/src/loaders/program-accounts.ts
  packages/rpc-graphql/src/loaders/transaction.ts
Labels: community, stale

#1973 refactor(experimental): move rpc-transport type tests into `src`
  packages/rpc-transport/src/__typetests__/methods-api-typetest.ts
  packages/rpc-transport/src/__typetests__/subscriptions-api-typetest.ts
Labels: community, stale

#2015 refactor(experimental): fix memo instructions in GraphQL
  packages/rpc-graphql/src/__tests__/__setup__.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/loaders/transformers/transaction.ts
  packages/rpc-graphql/src/schema/instruction.ts
Labels: community

#2016 refactor(experimental): refactor GraphQL `QueryArgs` to `LoaderArgs`
  packages/rpc-graphql/src/context.ts
  packages/rpc-graphql/src/loaders/account.ts
  packages/rpc-graphql/src/loaders/block.ts
  packages/rpc-graphql/src/loaders/program-accounts.ts
  packages/rpc-graphql/src/loaders/transaction.ts
  packages/rpc-graphql/src/loaders/transformers/account.ts
  packages/rpc-graphql/src/resolvers/account.ts
  packages/rpc-graphql/src/resolvers/block.ts
  packages/rpc-graphql/src/schema/account.ts
  packages/rpc-graphql/src/schema/block.ts
  packages/rpc-graphql/src/schema/index.ts
  packages/rpc-graphql/src/schema/program-accounts.ts
  packages/rpc-graphql/src/schema/transaction.ts
Labels: community

#2023 refactor(experimental): refactor GraphQL doc comments
  packages/rpc-graphql/src/schema/account.ts
  packages/rpc-graphql/src/schema/block.ts
  packages/rpc-graphql/src/schema/instruction.ts
  packages/rpc-graphql/src/schema/transaction.ts
Labels: community

#2020 refactor(experimental): add support for variable-sized items in remainder-sized codecs
  packages/codecs-data-structures/src/__tests__/array-test.ts
  packages/codecs-data-structures/src/__tests__/map-test.ts
  packages/codecs-data-structures/src/__tests__/set-test.ts
  packages/codecs-data-structures/src/__typetests__/array-typetest.ts
  packages/codecs-data-structures/src/__typetests__/map-typetest.ts
  packages/codecs-data-structures/src/__typetests__/set-typetest.ts
  packages/codecs-data-structures/src/array.ts
  packages/codecs-data-structures/src/map.ts
  packages/codecs-data-structures/src/set.ts
Labels: community

#2006 feat: Remove bailout behavior from missing sig func
  packages/signers/src/__tests__/sign-transaction-test.ts
  packages/transactions/src/__tests__/signatures-test.ts
  packages/transactions/src/signatures.ts
Labels: community

#2036 nit: Add comment specifying encoding of addresses
  packages/library-legacy/src/connection.ts
Labels: community

#2032 refactor(experimental): add @solana/codecs package
  packages/codecs/.gitignore
  packages/codecs/.prettierignore
  packages/codecs/LICENSE
  packages/codecs/README.md
  packages/codecs/package.json
  packages/codecs/src/index.ts
  packages/codecs/tsconfig.declarations.json
  packages/codecs/tsconfig.json
  pnpm-lock.yaml
Labels: community

#2033 refactor(experimental): add codecs to main library
  packages/library/README.md
  packages/library/package.json
  packages/library/src/__tests__/transaction-confirmation-strategy-nonce-test.ts
  packages/library/src/index.ts
  packages/library/src/transaction-confirmation-strategy-nonce.ts
  pnpm-lock.yaml
Labels: community

#2034 refactor(experimental): add programs and signers to main library
  packages/library/package.json
  packages/library/src/index.ts
  pnpm-lock.yaml
Labels: community

#2039 refactor(experimental): Document codec packages
  packages/codecs-core/README.md
  packages/codecs-data-structures/README.md
  packages/codecs-numbers/README.md
  packages/codecs-strings/README.md
  packages/codecs/README.md
  packages/options/README.md
Labels: community

#2062 refactor(experimental): graphql: fix `blockTime` in transaction schema
  packages/rpc-graphql/src/__tests__/block-tests.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/schema/block.ts
  packages/rpc-graphql/src/schema/transaction.ts
Labels: community

#2051 refactor(experimental): decouple @solana/accounts from @solana/rpc-core
  packages/accounts/package.json
  packages/accounts/src/__tests__/__setup__.ts
  packages/accounts/src/__typetests__/fetch-account-typetest.ts
  packages/accounts/src/fetch-account.ts
  packages/accounts/src/parse-account.ts
  packages/accounts/src/rpc-api/common.ts
  packages/accounts/src/rpc-api/getAccountInfo.ts
  packages/accounts/src/rpc-api/getMultipleAccounts.ts
  packages/accounts/src/rpc-api/index.ts
  pnpm-lock.yaml
Labels: community

#2045 refactor(experimental): graphql: shuffle around repository layout
  packages/rpc-graphql/src/__tests__/account-test.ts
  packages/rpc-graphql/src/__tests__/block-tests.ts
  packages/rpc-graphql/src/__tests__/program-accounts-test.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/context.ts
  packages/rpc-graphql/src/index.ts
  packages/rpc-graphql/src/rpc.ts
Labels: community

#2046 refactor(experimental): graphql: refactor resolvers into their own directory
  packages/rpc-graphql/src/index.ts
  packages/rpc-graphql/src/resolvers/account.ts
  packages/rpc-graphql/src/resolvers/block.ts
  packages/rpc-graphql/src/resolvers/index.ts
  packages/rpc-graphql/src/resolvers/instruction.ts
  packages/rpc-graphql/src/resolvers/root.ts
  packages/rpc-graphql/src/resolvers/scalars.ts
  packages/rpc-graphql/src/resolvers/transaction.ts
  packages/rpc-graphql/src/resolvers/types.ts
  packages/rpc-graphql/src/schema/account.ts
  packages/rpc-graphql/src/schema/block.ts
  packages/rpc-graphql/src/schema/common/inputs.ts
  packages/rpc-graphql/src/schema/common/scalars.ts
  packages/rpc-graphql/src/schema/common/types.ts
  packages/rpc-graphql/src/schema/index.ts
  packages/rpc-graphql/src/schema/instruction.ts
  packages/rpc-graphql/src/schema/root.ts
  packages/rpc-graphql/src/schema/transaction.ts
Labels: community

#2064 refactor(experimental): graphql: refactor transforms out of loaders and into resolvers
  packages/rpc-graphql/src/__tests__/block-tests.ts
  packages/rpc-graphql/src/context.ts
  packages/rpc-graphql/src/loaders/account.ts
  packages/rpc-graphql/src/loaders/block.ts
  packages/rpc-graphql/src/loaders/common/cache-key-fn.ts
  packages/rpc-graphql/src/loaders/index.ts
  packages/rpc-graphql/src/loaders/loader.ts
  packages/rpc-graphql/src/loaders/program-accounts.ts
  packages/rpc-graphql/src/loaders/transaction.ts
  packages/rpc-graphql/src/loaders/transformers/account.ts
  packages/rpc-graphql/src/loaders/transformers/block.ts
  packages/rpc-graphql/src/loaders/transformers/transaction.ts
  packages/rpc-graphql/src/resolvers/account.ts
  packages/rpc-graphql/src/resolvers/block.ts
  packages/rpc-graphql/src/resolvers/index.ts
  packages/rpc-graphql/src/resolvers/program-accounts.ts
  packages/rpc-graphql/src/resolvers/resolve-info.ts
  packages/rpc-graphql/src/resolvers/root.ts
  packages/rpc-graphql/src/resolvers/transaction.ts
Labels: community

#2047 refactor(experimental): graphql: refactor entrypoint to fix caching
  packages/rpc-graphql/src/__tests__/account-test.ts
  packages/rpc-graphql/src/__tests__/block-tests.ts
  packages/rpc-graphql/src/__tests__/program-accounts-test.ts
  packages/rpc-graphql/src/__tests__/transaction-tests.ts
  packages/rpc-graphql/src/context.ts
  packages/rpc-graphql/src/index.ts
Labels: community
